const STATE={user:null,isAdmin:false,schoolLogo:localStorage.getItem('schoolLogo')||'',schoolName:localStorage.getItem('schoolName')||'โรงเรียนดาราวิทยาลัย',unassignedQueue:[],students:[{id:'66001',name:'นายสมชาย ใจดี',room:'ม.3/1',no:1,score:86},{id:'66002',name:'น.ส.วิภา สวยงาม',room:'ม.3/1',no:2,score:93},{id:'66003',name:'ด.ช.ปิยะ มีสุข',room:'ม.3/1',no:3,score:54},{id:'66004',name:'น.ส.กนกวรรณ ดีมาก',room:'ม.3/1',no:4,score:78},{id:'66005',name:'นายอนันต์ รักเรียน',room:'ม.3/1',no:5,score:70},{id:'66006',name:'น.ส.สุภาพร แสนดี',room:'ม.3/2',no:1,score:88},{id:'66007',name:'ด.ช.ภานุพงศ์ เก่งมาก',room:'ม.3/2',no:2,score:62}],exams:[{id:'e1',name:'คณิตศาสตร์ ม.3 ปลายภาค',room:'ม.3/1',questions:30,done:40,total:40,avg:73.4,status:'done'},{id:'e2',name:'วิทยาศาสตร์ ม.2',room:'ม.3/2',questions:40,done:28,total:38,avg:70,status:'inprogress'}],selectedExam:'e1',numQ:30,choiceType:'ก-ง',fillRanges:[],answerKey:{},designStep:1,selectedStudentForAssign:null,scanResultData:null};
STATE.unassignedQueue=[{imgEmoji:'📄',note:'QR Code อ่านไม่ได้ — กระดาษย่น'},{imgEmoji:'📋',note:'ไม่มีชื่อและไม่มี QR'},{imgEmoji:'📃',note:'QR Code ถูกลบออก'}];
function updateClock(){const n=new Date();const s=n.getHours().toString().padStart(2,'0')+':'+n.getMinutes().toString().padStart(2,'0');document.querySelectorAll('.sb-time').forEach(e=>e.textContent=s)}
setInterval(updateClock,15000);
function showScreen(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));const e=document.getElementById(id);if(e){e.classList.add('active');window.scrollTo(0,0)}}
function openSheet(id){document.getElementById(id)?.classList.add('open')}
function closeSheet(id){document.getElementById(id)?.classList.remove('open')}
function closeSheetOnBg(e,id){if(e.target.classList.contains('sheet-overlay'))closeSheet(id)}
let _tt;function toast(msg,dur=2600){const e=document.getElementById('toast');e.textContent=msg;e.classList.add('show');clearTimeout(_tt);_tt=setTimeout(()=>e.classList.remove('show'),dur)}
function loginGoogle(){toast('กำลังเชื่อมต่อ Google...');setTimeout(()=>{STATE.user={name:'คุณครูสมศรี มีสุข',email:'somsri@daravit.ac.th',initial:'ส'};afterLogin()},1000)}
function loginDemo(){STATE.user={name:'Demo Teacher',email:'demo@daravit.ac.th',initial:'D'};afterLogin();toast('Demo Mode')}
function afterLogin(){renderProfileHeader();renderStudentList();renderItemAnalysis();renderUnassignedBanner();showScreen('screen-home')}
function logout(){if(confirm('ออกจากระบบ?')){STATE.user=null;showScreen('screen-login')}}
function tryAdminLogin(){const p=document.getElementById('admin-pin').value.trim();if(p==='100625'){STATE.isAdmin=true;closeSheet('sheet-admin-login');renderAdminPanel();showScreen('screen-admin');toast('🔑 Admin Panel')}else{document.getElementById('admin-pin-err').style.display='block'}}
function renderAdminPanel(){const prev=document.getElementById('logo-preview-img');if(prev){const s=localStorage.getItem('schoolLogo');prev.innerHTML=s?`<img src="${s}" alt="logo">`:'🏫 ยังไม่มีโลโก้'}
const sn=document.getElementById('admin-school-name');if(sn)sn.value=localStorage.getItem('schoolName')||'โรงเรียนดาราวิทยาลัย';const su=document.getElementById('admin-logo-url');if(su)su.value=localStorage.getItem('schoolLogo')||''}
function previewLogoFromUrl(){const url=document.getElementById('admin-logo-url').value.trim();if(!url)return;document.getElementById('logo-preview-img').innerHTML=`<img src="${url}" onerror="this.parentElement.innerHTML='❌ URL ไม่ถูกต้อง'" alt="logo">`}
function saveAdminSettings(){const u=document.getElementById('admin-logo-url').value.trim();const n=document.getElementById('admin-school-name').value.trim();if(u)localStorage.setItem('schoolLogo',u);if(n)localStorage.setItem('schoolName',n);STATE.schoolLogo=u;STATE.schoolName=n;toast('💾 บันทึกแล้ว');setTimeout(()=>showScreen('screen-home'),800)}
function renderProfileHeader(){if(!STATE.user)return;const m={'profile-name':STATE.user.name,'profile-email':STATE.user.email,'profile-av':STATE.user.initial,'header-avatar':STATE.user.initial};Object.entries(m).forEach(([k,v])=>{const e=document.getElementById(k);if(e)e.textContent=v})}
function renderUnassignedBanner(){const e=document.getElementById('unassigned-count');if(e)e.textContent=STATE.unassignedQueue.length}
function setQ(n,btn){STATE.numQ=n;btn.closest('.toggle-group')?.querySelectorAll('.toggle-btn').forEach(b=>b.classList.remove('active'));btn.classList.add('active')}
function setChoice(t,btn){STATE.choiceType=t;btn.closest('.toggle-group')?.querySelectorAll('.toggle-btn').forEach(b=>b.classList.remove('active'));btn.classList.add('active')}
function addFillRange(){const f=document.getElementById('fill-from').value.trim(),t=document.getElementById('fill-to').value.trim();if(!f)return;STATE.fillRanges.push(t?`ข้อ ${f}–${t}`:`ข้อ ${f}`);document.getElementById('fill-from').value='';document.getElementById('fill-to').value='';renderFillChips()}
function removeFill(i){STATE.fillRanges.splice(i,1);renderFillChips()}
function renderFillChips(){const c=document.getElementById('fill-chips');if(c)c.innerHTML=STATE.fillRanges.map((r,i)=>`<span class="chip">${r}<span class="chip-x" onclick="removeFill(${i})">✕</span></span>`).join('')}
function nextDesignStep(s){STATE.designStep=s;['d-step1','d-step2','d-step3'].forEach((id,i)=>{const e=document.getElementById(id);if(e)e.style.display=(i+1===s)?'block':'none'});['sdot1','sdot2','sdot3'].forEach((id,i)=>{const e=document.getElementById(id);if(!e)return;e.className='step-dot '+(i+1<s?'done':i+1===s?'active':'todo');e.textContent=i+1<s?'✓':i+1});['sline1','sline2'].forEach((id,i)=>{const e=document.getElementById(id);if(e)e.className='step-line'+(s>i+2?' done':'')});if(s===2){buildSheetPreview();buildAnswerKeyGrid()}if(s===3)toast('✅ บันทึกใน Google Drive แล้ว!');window.scrollTo(0,0)}
function getChoices(){return({'ก-ง':['ก','ข','ค','ง'],'A-D':['A','B','C','D'],'A-E':['A','B','C','D','E'],'1-4':['1','2','3','4']})[STATE.choiceType]||['ก','ข','ค','ง']}
function buildSheetPreview(){const ch=getChoices();const title=document.getElementById('exam-name-input')?.value||'ชุดข้อสอบ';const t=document.getElementById('preview-title');if(t)t.textContent=title;const lp=document.getElementById('preview-logo');if(lp)lp.innerHTML=STATE.schoolLogo?`<img src="${STATE.schoolLogo}" style="height:30px" alt="logo">`:`<div style="font-size:12px;font-weight:800;color:var(--red)">${STATE.schoolName}</div>`;const grid=document.getElementById('preview-grid');if(!grid)return;let html='';for(let i=1;i<=Math.min(STATE.numQ,20);i++){html+=`<div style="display:flex;align-items:center;gap:4px;padding:2px 0"><span style="font-size:10px;font-weight:700;min-width:18px;color:var(--text3)">${i}.</span>${ch.map(c=>`<div class="bubble${Math.random()>.75?' filled':''}">${c}</div>`).join('')}</div>`}if(STATE.numQ>20)html+=`<div style="font-size:10px;color:var(--text3);padding:4px;grid-column:span 2;text-align:center">…อีก ${STATE.numQ-20} ข้อ</div>`;grid.innerHTML=html}
function buildAnswerKeyGrid(){const ch=getChoices();const grid=document.getElementById('answer-key-grid');if(!grid)return;let html='';for(let i=1;i<=STATE.numQ;i++){const sel=STATE.answerKey[i]||ch[0];html+=`<div><div style="font-size:11px;font-weight:700;color:var(--text3);text-align:center;margin-bottom:3px">${i}</div><select class="field-select" style="padding:7px;font-size:12px;text-align:center" onchange="STATE.answerKey[${i}]=this.value">${ch.map(c=>`<option value="${c}"${sel===c?' selected':''}>${c}</option>`).join('')}</select></div>`}grid.innerHTML=html}
function startScan(){toast('📷 เปิดกล้อง...');setTimeout(()=>{toast('🔍 วิเคราะห์กระดาษ...');setTimeout(()=>{const qrOk=Math.random()>0.35;if(qrOk)showScanResult({student:STATE.students[0],score:26,total:30});else showUnassignedFlow()},1500)},700)}
function showScanResult(data){STATE.scanResultData=data;const grid=document.getElementById('result-grid');if(!grid)return;const correct=[1,3,4,6,7,8,10,11,12,13,14,15,16,17,18,20,21,22,23,24,25,26,27,28,29,30];const ch=getChoices();let html='';for(let i=1;i<=data.total;i++){const ok=correct.includes(i);const a=ch[(i-1)%ch.length];html+=`<div class="ans-cell ${ok?'ok':'bad'}"><span class="q-n">${i}</span><span class="q-a">${a}</span></div>`}grid.innerHTML=html;['result-score','result-student','result-pct','result-id'].forEach((id,i)=>{const e=document.getElementById(id);if(!e)return;e.textContent=[`${data.score}/${data.total}`,data.student.name,`${((data.score/data.total)*100).toFixed(1)}%`,`รหัส: ${data.student.id} • ${data.student.room}`][i]});openSheet('sheet-scan-result');toast(`🎉 ตรวจสำเร็จ ${data.score}/${data.total}`)}
function showUnassignedFlow(){const e={imgEmoji:'📄',note:'QR อ่านไม่ได้ — เพิ่งถ่าย'};STATE.unassignedQueue.push(e);STATE.scanResultData={queueIndex:STATE.unassignedQueue.length-1};renderUnassignedBanner();renderStudentPickList();openSheet('sheet-assign');toast('⚠️ ระบุตัวนักเรียนไม่ได้ — กรุณาเลือกชื่อ',3500)}
function openUnassignedQueue(){renderQueueList();openSheet('sheet-queue')}
function renderQueueList(){const c=document.getElementById('queue-list');if(!c)return;if(!STATE.unassignedQueue.length){c.innerHTML='<div style="text-align:center;padding:40px;color:var(--text3)">🎉 ไม่มีกระดาษค้างระบุ</div>';return}c.innerHTML=STATE.unassignedQueue.map((q,i)=>`<div class="queue-card"><div class="queue-header orange"><div><div style="font-size:15px;font-weight:700">กระดาษ #${i+1}</div><div style="font-size:12px;opacity:0.85">${q.note}</div></div><button class="btn btn-xs" style="background:rgba(255,255,255,0.2);color:#fff;border:none;cursor:pointer" onclick="openAssignForQueue(${i})">ระบุชื่อ</button></div><div class="queue-img-placeholder">${q.imgEmoji}</div><div class="queue-body"><div style="font-size:13px;color:var(--text3)">แตะ "ระบุชื่อ" เพื่อเลือกนักเรียน</div></div></div>`).join('')}
function openAssignForQueue(idx){STATE.scanResultData={queueIndex:idx};STATE.selectedStudentForAssign=null;renderStudentPickList();closeSheet('sheet-queue');setTimeout(()=>openSheet('sheet-assign'),200)}
function renderStudentPickList(){const c=document.getElementById('student-pick-list');if(!c)return;const colors=['#C8102E','#EC4899','#F59E0B','#10B981','#8B5CF6','#0A84FF'];c.innerHTML=STATE.students.map((s,i)=>`<div class="student-pick-row" onclick="selectStudentForAssign('${s.id}')"><div class="spick-check" id="spick-${s.id}"></div><div class="s-avatar" style="width:36px;height:36px;font-size:14px;background:linear-gradient(135deg,${colors[i%6]},${colors[(i+2)%6]})">${s.name[3]||'?'}</div><div style="flex:1"><div style="font-size:14px;font-weight:600">${s.name}</div><div style="font-size:12px;color:var(--text3)">รหัส: ${s.id} • ${s.room}</div></div></div>`).join('')}
function selectStudentForAssign(id){STATE.selectedStudentForAssign=id;document.querySelectorAll('.spick-check').forEach(e=>{e.className='spick-check';e.textContent=''});const el=document.getElementById(`spick-${id}`);if(el){el.className='spick-check selected';el.textContent='✓'}}
function confirmAssign(){if(!STATE.selectedStudentForAssign){toast('⚠️ กรุณาเลือกนักเรียนก่อน');return}const s=STATE.students.find(x=>x.id===STATE.selectedStudentForAssign);const idx=STATE.scanResultData?.queueIndex;if(idx!==undefined)STATE.unassignedQueue.splice(idx,1);renderUnassignedBanner();closeSheet('sheet-assign');toast(`✅ กำหนดให้ ${s.name} เรียบร้อย`)}
function renderStudentList(filter='',room='all'){const c=document.getElementById('student-list');if(!c)return;let list=STATE.students;if(room!=='all')list=list.filter(s=>s.room===room);if(filter)list=list.filter(s=>s.name.includes(filter)||s.id.includes(filter));if(!list.length){c.innerHTML='<div style="text-align:center;padding:32px;color:var(--text3)">ไม่พบนักเรียน</div>';return}const cols=['#C8102E','#EC4899','#F59E0B','#10B981','#8B5CF6','#0A84FF','#FF6B00'];c.innerHTML=list.map((s,i)=>`<div class="list-row" style="background:var(--surface);border-radius:var(--r-lg);margin:0 16px 10px;box-shadow:var(--shadow)" onclick="openStudentDetail('${s.id}')"><div class="s-avatar" style="background:linear-gradient(135deg,${cols[i%7]},${cols[(i+2)%7]})">${s.name[3]||'?'}</div><div class="list-body"><div class="list-title">${s.name}</div><div class="list-sub">รหัส ${s.id} • ${s.room}</div></div><div style="text-align:right"><div style="font-size:20px;font-weight:800;color:${s.score>=80?'var(--success)':s.score>=60?'var(--red)':'var(--danger)'}">${s.score}</div><div style="font-size:11px;color:var(--text3)">คะแนน%</div></div></div>`).join('')}
function openStudentDetail(id){const s=STATE.students.find(x=>x.id===id);if(!s)return;['sd-name','sd-meta','sd-score','sd-pct'].forEach((eid,i)=>{const e=document.getElementById(eid);if(e)e.textContent=[s.name,`รหัส: ${s.id} • ${s.room}`,`${Math.round(s.score*30/100)}/30`,`${s.score}%`][i]});openSheet('sheet-student-detail')}
function filterStudentsByRoom(room,btn){btn.closest('.toggle-group')?.querySelectorAll('.toggle-btn').forEach(b=>b.classList.remove('active'));btn.classList.add('active');const q=document.querySelector('.search-field input')?.value||'';renderStudentList(q,room)}
function renderItemAnalysis(){const c=document.getElementById('item-analysis');if(!c)return;const data=[85,70,90,45,80,60,75,88,35,92,65,78,55,82,70,45,88,76,60,92,80,70,65,85,50,78,90,62,88,75];c.innerHTML=data.map((p,i)=>{const col=p>=80?'var(--success)':p>=60?'var(--info)':p>=40?'var(--warn)':'var(--danger)';return`<div class="ia-row"><span class="ia-num">${i+1}</span><div class="ia-track"><div class="ia-fill" style="width:${p}%;background:${col}"></div></div><span class="ia-pct" style="color:${col}">${p}%</span><span>${p>=80?'🟢':p>=60?'🔵':p>=40?'🟡':'🔴'}</span></div>`}).join('')}
document.addEventListener('DOMContentLoaded',()=>{updateClock();renderItemAnalysis()});
